describe('template spec', () => {
  beforeEach(() => {
    cy.visit('http://127.0.0.1:5502/')
  })

  context('Testes para desktop (Padrão)', () => {
    beforeEach(() => {

      cy.viewport(1000, 660);

    });

    /* ==== Test Created with Cypress Studio ==== */
    it('Testes para desktop', function () {
      /* ==== Generated with Cypress Studio ==== */
      cy.get('.img-logo').should('have.class', 'img-logo');
      cy.get('.img-logo').should('have.attr', 'src', './img/logo-empresa.png');
      cy.get('.img-logo').should('be.visible');
      cy.get('.importante').should('have.class', 'importante');
      cy.get('.importante').should('be.visible');
      cy.get('.barra').should('have.class', 'barra');
      cy.get('.barra').should('be.visible');
      cy.get('.Icone-Perfil').should('have.class', 'Icone-Perfil');
      cy.get('.Icone-Perfil').click();
      cy.get('.Icone-Perfil').should('have.attr', 'src', './img/imagem-perfil.png');
      cy.get('.Icone-Perfil').should('have.attr', 'height', '35px');
      cy.get('.Icone-Perfil').should('be.visible');
      cy.get('.Icone-carrinho').should('have.class', 'Icone-carrinho');
      cy.get('.Icone-carrinho').should('have.attr', 'src', './img/carrinho-de-compras-6.png');
      cy.get('.Icone-carrinho').should('have.attr', 'height', '35px');
      cy.get('.Icone-carrinho').should('be.visible');
      cy.get('.Icone-Pedidos').should('have.class', 'Icone-Pedidos');
      cy.get('.Icone-Pedidos').should('have.attr', 'height', '35px');
      cy.get('.Icone-Pedidos').should('be.visible');
      cy.get('.search-txt').should('have.class', 'search-txt');
      cy.get('.search-txt').should('have.attr', 'type', 'text');
      cy.get('.search-txt').should('have.attr', 'placeholder', 'Pesquisa');
      cy.get('.search-txt').should('be.visible');
      cy.get('.search-txt').should('be.enabled');
      cy.get('.search-txt').should('not.be.checked');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(1)').should('be.visible');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(1)').should('have.text', 'HOME');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(2)').should('have.text', 'PRODUTOS');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(2)').click();
      cy.get('.headerPagina > :nth-child(2) > :nth-child(2)').should('be.visible');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(3)').should('have.text', 'SERVIÇOS');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(3)').should('be.visible');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(4)').should('have.text', 'LOJAS');
      cy.get('.s1 > img').click();
      cy.get('.headerPagina > :nth-child(2) > :nth-child(4)').should('be.visible');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(5)').should('have.text', 'PERFIL');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(5)').should('be.visible');
      cy.get('.sloganHeader').should('have.text', 'PERSONALIZE SEU CARRO COM AS MELHORES PEÇAS E MÃO DE OBRA ESPECIALIZADA');
      cy.get('.sloganHeader').should('have.class', 'sloganHeader');
      cy.get('.sloganHeader').should('be.visible');
      cy.get('.s1 > img').should('have.attr', 'src', './img/1.jpg');
      cy.get('.s1 > img').should('be.visible');
      cy.get('[for="slide1"]').should('have.class', 'bar');
      cy.get('[for="slide1"]').should('have.attr', 'for', 'slide1');
      cy.get('[for="slide1"]').should('be.visible');
      cy.get('[for="slide2"]').click();
      cy.get(':nth-child(7) > img').should('have.attr', 'src', './img/2.jpg');
      cy.get(':nth-child(7) > img').should('be.visible');
      cy.get('[for="slide2"]').should('have.class', 'bar');
      cy.get('[for="slide2"]').should('have.attr', 'for', 'slide2');
      cy.get('[for="slide2"]').should('be.visible');
      cy.get('[for="slide3"]').click();
      cy.get(':nth-child(8) > img').should('have.attr', 'src', './img/3.jpg');
      cy.get(':nth-child(8) > img').should('be.visible');
      cy.get('[for="slide3"]').should('have.class', 'bar');
      cy.get('[for="slide3"]').should('have.attr', 'for', 'slide3');
      cy.get('[for="slide3"]').should('be.visible');
      cy.get('[for="slide4"]').click();
      cy.get(':nth-child(9) > img').should('have.attr', 'src', './img/4.jpg');
      cy.get(':nth-child(9) > img').should('be.visible');
      cy.get('[for="slide4"]').should('have.class', 'bar');
      cy.get('[for="slide4"]').should('have.attr', 'for', 'slide4');
      cy.get('[for="slide4"]').should('be.visible');
      cy.get('[for="slide4"]').click();
      cy.get('[for="slide5"]').click();
      cy.get(':nth-child(10) > img').should('have.attr', 'src', './img/5.jpg');
      cy.get(':nth-child(10) > img').should('be.visible');
      cy.get('[for="slide5"]').should('have.class', 'bar');
      cy.get('[for="slide5"]').should('have.attr', 'for', 'slide5');
      cy.get('[for="slide5"]').should('be.visible');
      cy.get('.headerPagina').should('have.class', 'headerPagina');
      cy.get('.headerPagina').should('be.visible');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('have.class', 'imgProduto');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('have.attr', 'src', './img/peca-escapamento.svg');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('have.attr', 'width', '150px');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('have.attr', 'height', '200px');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('be.visible');
      cy.get(':nth-child(1) > .nomeProduto').should('have.text', 'Escap. coração');
      cy.get(':nth-child(1) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(1) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(1) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(1) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(1) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(1) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(1) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get('.containerPecas > :nth-child(1)').should('have.class', 'pecas');
      cy.get('.containerPecas > :nth-child(1)').should('be.visible');
      cy.get(':nth-child(2) > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(2) > .imgProduto').should('have.attr', 'src', './img/lanterna.svg');
      cy.get(':nth-child(2) > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(2) > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(2) > .nomeProduto').should('have.text', 'Lanterna Colorida');
      cy.get(':nth-child(2) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(2) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(2) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(2) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(2) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(2) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(2) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(2) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(2) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(2) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(2) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get('.containerPecas > :nth-child(2)').should('have.class', 'pecas');
      cy.get(':nth-child(3) > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(3) > .imgProduto').should('have.attr', 'src', './img/led-interno.svg');
      cy.get(':nth-child(3) > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(3) > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(3) > .imgProduto').should('be.visible');
      cy.get(':nth-child(3) > .nomeProduto').should('have.text', 'Led Interno');
      cy.get(':nth-child(3) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(3) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(3) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(3) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(3) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(3) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(3) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(3)').should('have.class', 'pecas');
      cy.get(':nth-child(4) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(4) > a > .imgProduto').should('have.attr', 'src', './img/farol-anjo.svg');
      cy.get(':nth-child(4) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(4) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(4) > a > .imgProduto').should('be.visible');
      cy.get(':nth-child(4) > .nomeProduto').should('have.text', 'Farol Olho de Anjo');
      cy.get(':nth-child(4) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(4) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(4) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(4) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(4) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(7) > a > .imgProduto').click();
      cy.get('[href="index.html"]').click();
      cy.get(':nth-child(4) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(4) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(4) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(4)').should('have.class', 'pecas');
      cy.get(':nth-child(5) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(5) > a > .imgProduto').should('have.attr', 'src', './img/capa-banco.svg');
      cy.get(':nth-child(5) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(5) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(5) > a > .imgProduto').should('be.visible');
      cy.get(':nth-child(5) > .nomeProduto').should('have.text', 'Capa de Banco');
      cy.get(':nth-child(5) > .nomeProduto').click();
      cy.get(':nth-child(5) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(5) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(5) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(5) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(5) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(5) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(5) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(5)').should('have.class', 'pecas');
      cy.get(':nth-child(6) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(6) > a > .imgProduto').should('have.attr', 'src', 'img/freio-mao.svg');
      cy.get(':nth-child(6) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(6) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(6) > a > .imgProduto').should('be.visible');
      cy.get(':nth-child(6) > .nomeProduto').should('have.text', 'Freios de Mão');
      cy.get(':nth-child(6) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(6) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(6) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(6) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(6) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(6) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(6) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(6)').should('have.class', 'pecas');
      cy.get(':nth-child(7) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(7) > a > .imgProduto').should('have.attr', 'src', './img/disco-freio.svg');
      cy.get(':nth-child(7) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(7) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(7) > a > .imgProduto').should('be.visible');
      cy.get(':nth-child(7) > .nomeProduto').should('have.text', 'Discos de Freio');
      cy.get(':nth-child(7) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(7) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(7) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(7) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(7) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(7) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(7) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(7) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(7) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(7) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(7)').should('have.class', 'pecas');
      cy.get(':nth-child(8) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(8) > a > .imgProduto').should('have.attr', 'src', './img/parachoque.svg');
      cy.get(':nth-child(8) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(8) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(8) > .nomeProduto').should('have.text', 'Parachoques');
      cy.get(':nth-child(8) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(8) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(8) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(8) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(8) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(8) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(8) > .infosProdutos').should('be.visible');
      // cy.get('.containerPecas > :nth-child(8)').click();
      cy.get('.containerPecas > :nth-child(8)').should('have.class', 'pecas');
      cy.get('.containerPecas').should('have.class', 'containerPecas');
      cy.get('.containerPecas').should('be.visible');
      cy.get('.titulo-superior').should('have.text', 'CONHEÇA NOSSOS SERVIÇOS');
      cy.get('.titulo-superior').should('have.class', 'titulo-superior');
      cy.get('.titulo-superior').should('be.visible');
      cy.get('.container-servicos').should('have.class', 'container-servicos');
      cy.get('.container-servicos').should('be.visible');
      cy.get('.container-servicos > :nth-child(1)').should('have.class', 'contido-servicos');
      cy.get('.container-servicos > :nth-child(1)').should('be.visible');
      cy.get(':nth-child(1) > :nth-child(1) > .controle-imagens').click();
      cy.get(':nth-child(1) > :nth-child(1) > .controle-imagens').should('have.class', 'controle-imagens');
      cy.get(':nth-child(1) > :nth-child(1) > .controle-imagens').should('have.attr', 'src', './img/icone-servicos.svg');
      cy.get(':nth-child(1) > :nth-child(1) > .controle-imagens').should('be.visible');
      cy.get(':nth-child(1) > .acessos').should('have.text', 'Serviços');
      cy.get(':nth-child(1) > .acessos').should('have.class', 'acessos');
      cy.get(':nth-child(1) > .acessos').should('have.attr', 'href', '#');
      cy.get(':nth-child(1) > .acessos').should('be.visible');
      cy.get('.container-servicos > :nth-child(1)').should('have.text', '\n                \n                \n                Serviços\n            ');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(1)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(1)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(1)').should('be.visible');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(2)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(2)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(2)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(2)').should('be.visible');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(3)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(3)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(3)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(3)').should('be.visible');
      cy.get('.container-servicos > :nth-child(2)').should('have.text', '\n                \n                \n                \n            ');
      cy.get('.container-servicos > :nth-child(2)').click();
      cy.get('.container-servicos > :nth-child(2)').should('have.class', 'pontos-servicos');
      cy.get('.container-servicos > :nth-child(2)').should('be.visible');
      cy.get('.container-servicos > :nth-child(3)').should('have.text', '\n                \n                \n                Lojas\n            ');
      cy.get('.container-servicos > :nth-child(3)').should('have.class', 'contido-servicos');
      cy.get('.container-servicos > :nth-child(3)').should('be.visible');
      cy.get(':nth-child(3) > :nth-child(1) > .controle-imagens').should('have.class', 'controle-imagens');
      cy.get(':nth-child(3) > :nth-child(1) > .controle-imagens').should('have.attr', 'src', './img/icone-lojas.svg');
      cy.get(':nth-child(3) > :nth-child(1) > .controle-imagens').should('be.visible');
      cy.get(':nth-child(3) > .acessos').should('have.text', 'Lojas');
      cy.get(':nth-child(3) > .acessos').should('have.class', 'acessos');
      cy.get(':nth-child(3) > .acessos').should('have.class', 'lojasIcone');
      cy.get(':nth-child(3) > .acessos').should('have.attr', 'href', '#');
      cy.get(':nth-child(3) > .acessos').should('be.visible');
      cy.get('.container-servicos > :nth-child(3)').should('have.text', '\n                \n                \n                Lojas\n            ');
      cy.get('.container-servicos > :nth-child(3)').should('have.class', 'contido-servicos');
      cy.get('.container-servicos > :nth-child(3)').should('be.visible');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(1)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(1)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(1)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(1)').should('be.visible');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').click();
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').should('be.visible');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(3)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(3)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(3)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(3)').should('be.visible');
      cy.get(':nth-child(5) > :nth-child(1) > .controle-imagens').should('have.class', 'controle-imagens');
      cy.get(':nth-child(5) > :nth-child(1) > .controle-imagens').should('have.attr', 'src', './img/icone-promocoes.svg');
      cy.get(':nth-child(5) > :nth-child(1) > .controle-imagens').should('be.visible');
      cy.get(':nth-child(5) > .acessos').should('have.text', 'Promoções');
      cy.get(':nth-child(5) > .acessos').should('have.class', 'acessos');
      cy.get(':nth-child(5) > .acessos').click();
      cy.get(':nth-child(5) > .acessos').should('have.attr', 'href', '#');
      cy.get(':nth-child(5) > .acessos').should('be.visible');
      cy.get('.container-servicos > :nth-child(5)').should('be.visible');
      cy.get('.footerSpace').click();
      cy.get('.footerSpace').should('have.class', 'footerSpace');
      cy.get('.footerSpace').should('be.visible');
      cy.get('#email').click();
      cy.get('#divEmail').should('have.class', 'footerContainer');
      cy.get('#divEmail').should('have.id', 'divEmail');
      cy.get('#divEmail').click();
      cy.get('#divEmail').should('be.visible');
      cy.get('#email').should('have.class', 'barraEmail');
      cy.get('#email').click();
      cy.get('#email').should('have.id', 'email');
      cy.get('#email').should('have.attr', 'type', 'email');
      cy.get('#email').click();
      cy.get('#email').should('have.attr', 'placeholder', 'Digite aqui seu email');
      cy.get('#email').should('be.visible');
      cy.get('#email').should('be.enabled');
      cy.get('#email').should('not.be.checked');
      cy.get('.botaoEmail').should('have.text', 'Login');
      cy.get('.botaoEmail').should('have.class', 'botaoEmail');
      cy.get('.botaoEmail').should('have.attr', 'type', 'submit');
      cy.get('.botaoEmail').should('be.visible');
      cy.get('.botaoEmail').should('be.enabled');
      cy.get('.redes-sociais').should('have.text', 'Midias Sociais');
      cy.get('.redes-sociais').should('have.class', 'redes-sociais');
      cy.get('.redes-sociais').should('be.visible');
      cy.get('.midias-sociais > :nth-child(1) > img').should('have.attr', 'src', './img/logo-discord.svg');
      cy.get('.midias-sociais > :nth-child(1) > img').should('be.visible');
      cy.get('.midias-sociais > :nth-child(2) > img').should('have.attr', 'src', './img/logo-instagram.svg');
      cy.get('.midias-sociais > :nth-child(2) > img').should('be.visible');
      cy.get('.midias-sociais > :nth-child(3) > img').should('have.attr', 'src', './img/logo-twitter.svg');
      cy.get('.midias-sociais > :nth-child(3) > img').should('be.visible');
      cy.get('.midias-sociais > :nth-child(4) > img').should('have.attr', 'src', './img/logo-youtube.svg');
      cy.get('.midias-sociais > :nth-child(4) > img').should('be.visible');
      cy.get('.midias-sociais').should('have.class', 'midias-sociais');
      cy.get('.midias-sociais').should('be.visible');
      cy.get('.copright-footer > h1').should('have.text', 'Copyright© 2023 Cyber-Motors. Todos os direitos reservados.');
      cy.get('.copright-footer > h1').should('be.visible');
      cy.get('.copright-footer > p').should('have.text', 'Sede em SENAI-Ipiranga Rua. Moreira de Godói, 226 - Ipiranga, São Paulo - SP, 04266-060');
      cy.get('.copright-footer > p').should('be.visible');
      cy.get('.devs-names > h1').should('have.text', 'Desenvolvedores:');
      cy.get('.devs-names > h1').should('be.visible');
      cy.get('.devs-names > :nth-child(2)').should('have.text', 'Bruno Leite Dos Santos');
      cy.get('.devs-names > :nth-child(2)').should('be.visible');
      cy.get('.devs-names > :nth-child(3)').should('have.text', 'Caio Matuti Destazio');
      cy.get('.devs-names > :nth-child(3)').should('be.visible');
      cy.get('.devs-names > :nth-child(4)').should('have.text', 'Fabio Luiz Silva Costa');
      cy.get('.devs-names > :nth-child(4)').should('be.visible');
      cy.get('.devs-names > :nth-child(5)').should('have.text', 'Felipe Wilquem Da Silva');
      cy.get('.devs-names > :nth-child(5)').should('be.visible');
      cy.get('.devs-names > :nth-child(6)').should('have.text', 'Gabriel Cavalcanti Barbosa');
      cy.get('.devs-names > :nth-child(6)').should('be.visible');
      cy.get('.devs-names > :nth-child(7)').should('have.text', 'Ingridy Estefany Moreno Souza Belini');
      cy.get('.devs-names > :nth-child(7)').should('be.visible');
      cy.get('.devs-names > :nth-child(8)').should('have.text', 'Melissa Vitória Da Silva Moya');
      cy.get('.devs-names > :nth-child(8)').should('be.visible');
      cy.get('.devs-names > :nth-child(9)').should('have.text', 'Nelson Zanferrari Sauer');
      cy.get('.devs-names > :nth-child(9)').should('be.visible');
      cy.get('.devs-names > :nth-child(10)').should('have.text', 'Renata Biagioni Wroblesk');
      cy.get('.devs-names > :nth-child(10)').should('be.visible');
      cy.get('.span-topo > a').should('have.text', 'Topo');
      cy.get('.span-topo > a').should('have.attr', 'href', '#topo-pagina');
      cy.get('.span-topo > a').should('be.visible');
      cy.get('.devs-names').should('have.class', 'devs-names');
      cy.get('.devs-names').should('be.visible');
      cy.get('.footerSpace').click();

      cy.get('footer').should('be.visible');
      /* ==== End Cypress Studio ==== */
    });
  });

  context('Testes para mobile (Secundario)', () => {
    beforeEach(() => {

      cy.viewport(480, 720);

    });

    it('Testes para Mobile', function () {
      /* ==== Generated with Cypress Studio ==== */
      cy.get('.img-logo').should('have.class', 'img-logo');
      cy.get('.img-logo').should('have.attr', 'src', './img/logo-empresa.png');
      cy.get('.img-logo').should('be.visible');
      cy.get('.importante').should('have.class', 'importante');
      cy.get('.importante').should('be.visible');
      cy.get('.barra').should('have.class', 'barra');
      cy.get('.barra').should('be.visible');
      cy.get('.Icone-Perfil').should('have.class', 'Icone-Perfil');
      cy.get('.Icone-Perfil').click();
      cy.get('.Icone-Perfil').should('have.attr', 'src', './img/imagem-perfil.png');
      cy.get('.Icone-Perfil').should('have.attr', 'height', '35px');
      cy.get('.Icone-Perfil').should('be.visible');
      cy.get('.Icone-carrinho').should('have.class', 'Icone-carrinho');
      cy.get('.Icone-carrinho').should('have.attr', 'src', './img/carrinho-de-compras-6.png');
      cy.get('.Icone-carrinho').should('have.attr', 'height', '35px');
      cy.get('.Icone-carrinho').should('be.visible');
      cy.get('.Icone-Pedidos').should('have.class', 'Icone-Pedidos');
      cy.get('.Icone-Pedidos').should('have.attr', 'height', '35px');
      cy.get('.Icone-Pedidos').should('be.visible');
      cy.get('.search-txt').should('have.class', 'search-txt');
      cy.get('.search-txt').should('have.attr', 'type', 'text');
      cy.get('.search-txt').should('have.attr', 'placeholder', 'Pesquisa');
      cy.get('.search-txt').should('be.visible');
      cy.get('.search-txt').should('be.enabled');
      cy.get('.search-txt').should('not.be.checked');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(1)').should('be.visible');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(1)').should('have.text', 'HOME');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(2)').should('have.text', 'PRODUTOS');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(2)').click();
      cy.get('.headerPagina > :nth-child(2) > :nth-child(2)').should('be.visible');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(3)').should('have.text', 'SERVIÇOS');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(3)').should('be.visible');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(4)').should('have.text', 'LOJAS');
      cy.get('.s1 > img').click();
      cy.get('.headerPagina > :nth-child(2) > :nth-child(4)').should('be.visible');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(5)').should('have.text', 'PERFIL');
      cy.get('.headerPagina > :nth-child(2) > :nth-child(5)').should('be.visible');
      cy.get('.sloganHeader').should('have.text', 'PERSONALIZE SEU CARRO COM AS MELHORES PEÇAS E MÃO DE OBRA ESPECIALIZADA');
      cy.get('.sloganHeader').should('have.class', 'sloganHeader');
      cy.get('.sloganHeader').should('be.visible');
      cy.get('.s1 > img').should('have.attr', 'src', './img/1.jpg');
      cy.get('.s1 > img').should('be.visible');
      cy.get('[for="slide1"]').should('have.class', 'bar');
      cy.get('[for="slide1"]').should('have.attr', 'for', 'slide1');
      cy.get('[for="slide1"]').should('be.visible');
      cy.get('[for="slide2"]').click();
      cy.get(':nth-child(7) > img').should('have.attr', 'src', './img/2.jpg');
      cy.get(':nth-child(7) > img').should('be.visible');
      cy.get('[for="slide2"]').should('have.class', 'bar');
      cy.get('[for="slide2"]').should('have.attr', 'for', 'slide2');
      cy.get('[for="slide2"]').should('be.visible');
      cy.get('[for="slide3"]').click();
      cy.get(':nth-child(8) > img').should('have.attr', 'src', './img/3.jpg');
      cy.get(':nth-child(8) > img').should('be.visible');
      cy.get('[for="slide3"]').should('have.class', 'bar');
      cy.get('[for="slide3"]').should('have.attr', 'for', 'slide3');
      cy.get('[for="slide3"]').should('be.visible');
      cy.get('[for="slide4"]').click();
      cy.get(':nth-child(9) > img').should('have.attr', 'src', './img/4.jpg');
      cy.get(':nth-child(9) > img').should('be.visible');
      cy.get('[for="slide4"]').should('have.class', 'bar');
      cy.get('[for="slide4"]').should('have.attr', 'for', 'slide4');
      cy.get('[for="slide4"]').should('be.visible');
      cy.get('[for="slide4"]').click();
      cy.get('[for="slide5"]').click();
      cy.get(':nth-child(10) > img').should('have.attr', 'src', './img/5.jpg');
      cy.get(':nth-child(10) > img').should('be.visible');
      cy.get('[for="slide5"]').should('have.class', 'bar');
      cy.get('[for="slide5"]').should('have.attr', 'for', 'slide5');
      cy.get('[for="slide5"]').should('be.visible');
      cy.get('.headerPagina').should('have.class', 'headerPagina');
      cy.get('.headerPagina').should('be.visible');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('have.class', 'imgProduto');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('have.attr', 'src', './img/peca-escapamento.svg');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('have.attr', 'width', '150px');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('have.attr', 'height', '200px');
      cy.get('.containerPecas > :nth-child(1) > .imgProduto').should('be.visible');
      cy.get(':nth-child(1) > .nomeProduto').should('have.text', 'Escap. coração');
      cy.get(':nth-child(1) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(1) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(1) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(1) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(1) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(1) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(1) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(1) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(1) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get('.containerPecas > :nth-child(1)').should('have.class', 'pecas');
      cy.get('.containerPecas > :nth-child(1)').should('be.visible');
      cy.get(':nth-child(2) > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(2) > .imgProduto').should('have.attr', 'src', './img/lanterna.svg');
      cy.get(':nth-child(2) > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(2) > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(2) > .nomeProduto').should('have.text', 'Lanterna Colorida');
      cy.get(':nth-child(2) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(2) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(2) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(2) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(2) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(2) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(2) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(2) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(2) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(2) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(2) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get('.containerPecas > :nth-child(2)').should('have.class', 'pecas');
      cy.get(':nth-child(3) > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(3) > .imgProduto').should('have.attr', 'src', './img/led-interno.svg');
      cy.get(':nth-child(3) > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(3) > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(3) > .imgProduto').should('be.visible');
      cy.get(':nth-child(3) > .nomeProduto').should('have.text', 'Led Interno');
      cy.get(':nth-child(3) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(3) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(3) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(3) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(3) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(3) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(3) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(3) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(3)').should('have.class', 'pecas');
      cy.get(':nth-child(4) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(4) > a > .imgProduto').should('have.attr', 'src', './img/farol-anjo.svg');
      cy.get(':nth-child(4) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(4) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(4) > a > .imgProduto').should('be.visible');
      cy.get(':nth-child(4) > .nomeProduto').should('have.text', 'Farol Olho de Anjo');
      cy.get(':nth-child(4) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(4) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(4) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(4) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(4) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(7) > a > .imgProduto').click();
      cy.get('[href="index.html"]').click();
      cy.get(':nth-child(4) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(4) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(4) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(4) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(4)').should('have.class', 'pecas');
      cy.get(':nth-child(5) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(5) > a > .imgProduto').should('have.attr', 'src', './img/capa-banco.svg');
      cy.get(':nth-child(5) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(5) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(5) > a > .imgProduto').should('be.visible');
      cy.get(':nth-child(5) > .nomeProduto').should('have.text', 'Capa de Banco');
      cy.get(':nth-child(5) > .nomeProduto').click();
      cy.get(':nth-child(5) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(5) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(5) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(5) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(5) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(5) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(5) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(5) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(5)').should('have.class', 'pecas');
      cy.get(':nth-child(6) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(6) > a > .imgProduto').should('have.attr', 'src', 'img/freio-mao.svg');
      cy.get(':nth-child(6) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(6) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(6) > a > .imgProduto').should('be.visible');
      cy.get(':nth-child(6) > .nomeProduto').should('have.text', 'Freios de Mão');
      cy.get(':nth-child(6) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(6) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(6) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(6) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(6) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(6) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(6) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(6) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(6)').should('have.class', 'pecas');
      cy.get(':nth-child(7) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(7) > a > .imgProduto').should('have.attr', 'src', './img/disco-freio.svg');
      cy.get(':nth-child(7) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(7) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(7) > a > .imgProduto').should('be.visible');
      cy.get(':nth-child(7) > .nomeProduto').should('have.text', 'Discos de Freio');
      cy.get(':nth-child(7) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(7) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(7) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(7) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(7) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(7) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(7) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(7) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(7) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(7) > .infosProdutos').should('be.visible');
      cy.get('.containerPecas > :nth-child(7)').should('have.class', 'pecas');
      cy.get(':nth-child(8) > a > .imgProduto').should('have.class', 'imgProduto');
      cy.get(':nth-child(8) > a > .imgProduto').should('have.attr', 'src', './img/parachoque.svg');
      cy.get(':nth-child(8) > a > .imgProduto').should('have.attr', 'width', '150px');
      cy.get(':nth-child(8) > a > .imgProduto').should('have.attr', 'height', '200px');
      cy.get(':nth-child(8) > .nomeProduto').should('have.text', 'Parachoques');
      cy.get(':nth-child(8) > .nomeProduto').should('have.class', 'nomeProduto');
      cy.get(':nth-child(8) > .nomeProduto').should('be.visible');
      cy.get(':nth-child(8) > .infosProdutos > .precoProduto').should('have.text', 'R$ xxx,xx');
      cy.get(':nth-child(8) > .infosProdutos > .precoProduto').should('have.class', 'precoProduto');
      cy.get(':nth-child(8) > .infosProdutos > .precoProduto').should('be.visible');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('have.class', 'coracao');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('have.attr', 'src', './img/icone-coracao-vazio.svg');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').click();
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('have.attr', 'src', 'img/icone-coracao-cheio.svg');
      cy.get(':nth-child(8) > .infosProdutos > .coracao').should('be.visible');
      cy.get(':nth-child(8) > .infosProdutos').should('have.class', 'infosProdutos');
      cy.get(':nth-child(8) > .infosProdutos').should('be.visible');
      // cy.get('.containerPecas > :nth-child(8)').click();
      cy.get('.containerPecas > :nth-child(8)').should('have.class', 'pecas');
      cy.get('.containerPecas').should('have.class', 'containerPecas');
      cy.get('.containerPecas').should('be.visible');
      cy.get('.titulo-superior').should('have.text', 'CONHEÇA NOSSOS SERVIÇOS');
      cy.get('.titulo-superior').should('have.class', 'titulo-superior');
      cy.get('.titulo-superior').should('be.visible');
      cy.get('.container-servicos').should('have.class', 'container-servicos');
      cy.get('.container-servicos').should('be.visible');
      cy.get('.container-servicos > :nth-child(1)').should('have.class', 'contido-servicos');
      cy.get('.container-servicos > :nth-child(1)').should('be.visible');
      cy.get(':nth-child(1) > :nth-child(1) > .controle-imagens').click();
      cy.get(':nth-child(1) > :nth-child(1) > .controle-imagens').should('have.class', 'controle-imagens');
      cy.get(':nth-child(1) > :nth-child(1) > .controle-imagens').should('have.attr', 'src', './img/icone-servicos.svg');
      cy.get(':nth-child(1) > :nth-child(1) > .controle-imagens').should('be.visible');
      cy.get(':nth-child(1) > .acessos').should('have.text', 'Serviços');
      cy.get(':nth-child(1) > .acessos').should('have.class', 'acessos');
      cy.get(':nth-child(1) > .acessos').should('have.attr', 'href', '#');
      cy.get(':nth-child(1) > .acessos').should('be.visible');
      cy.get('.container-servicos > :nth-child(1)').should('have.text', '\n                \n                \n                Serviços\n            ');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(1)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(1)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(1)').should('be.visible');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(2)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(2)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(2)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(2)').should('be.visible');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(3)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(3)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(3)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(2) > :nth-child(3)').should('be.visible');
      cy.get('.container-servicos > :nth-child(2)').should('have.text', '\n                \n                \n                \n            ');
      cy.get('.container-servicos > :nth-child(2)').click();
      cy.get('.container-servicos > :nth-child(2)').should('have.class', 'pontos-servicos');
      cy.get('.container-servicos > :nth-child(2)').should('be.visible');
      cy.get('.container-servicos > :nth-child(3)').should('have.text', '\n                \n                \n                Lojas\n            ');
      cy.get('.container-servicos > :nth-child(3)').should('have.class', 'contido-servicos');
      cy.get('.container-servicos > :nth-child(3)').should('be.visible');
      cy.get(':nth-child(3) > :nth-child(1) > .controle-imagens').should('have.class', 'controle-imagens');
      cy.get(':nth-child(3) > :nth-child(1) > .controle-imagens').should('have.attr', 'src', './img/icone-lojas.svg');
      cy.get(':nth-child(3) > :nth-child(1) > .controle-imagens').should('be.visible');
      cy.get(':nth-child(3) > .acessos').should('have.text', 'Lojas');
      cy.get(':nth-child(3) > .acessos').should('have.class', 'acessos');
      cy.get(':nth-child(3) > .acessos').should('have.class', 'lojasIcone');
      cy.get(':nth-child(3) > .acessos').should('have.attr', 'href', '#');
      cy.get(':nth-child(3) > .acessos').should('be.visible');
      cy.get('.container-servicos > :nth-child(3)').should('have.text', '\n                \n                \n                Lojas\n            ');
      cy.get('.container-servicos > :nth-child(3)').should('have.class', 'contido-servicos');
      cy.get('.container-servicos > :nth-child(3)').should('be.visible');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(1)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(1)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(1)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(1)').should('be.visible');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').click();
      cy.get('.container-servicos > :nth-child(4) > :nth-child(2)').should('be.visible');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(3)').should('have.class', 'espaco-pontos');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(3)').should('have.attr', 'src', './img/ponto-servicos.svg');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(3)').should('have.attr', 'width', '8px');
      cy.get('.container-servicos > :nth-child(4) > :nth-child(3)').should('be.visible');
      cy.get(':nth-child(5) > :nth-child(1) > .controle-imagens').should('have.class', 'controle-imagens');
      cy.get(':nth-child(5) > :nth-child(1) > .controle-imagens').should('have.attr', 'src', './img/icone-promocoes.svg');
      cy.get(':nth-child(5) > :nth-child(1) > .controle-imagens').should('be.visible');
      cy.get(':nth-child(5) > .acessos').should('have.text', 'Promoções');
      cy.get(':nth-child(5) > .acessos').should('have.class', 'acessos');
      cy.get(':nth-child(5) > .acessos').click();
      cy.get(':nth-child(5) > .acessos').should('have.attr', 'href', '#');
      cy.get(':nth-child(5) > .acessos').should('be.visible');
      cy.get('.container-servicos > :nth-child(5)').should('be.visible');
      cy.get('.footerSpace').click();
      cy.get('.footerSpace').should('have.class', 'footerSpace');
      cy.get('.footerSpace').should('be.visible');
      cy.get('#email').click();
      cy.get('#divEmail').should('have.class', 'footerContainer');
      cy.get('#divEmail').should('have.id', 'divEmail');
      cy.get('#divEmail').click();
      cy.get('#divEmail').should('be.visible');
      cy.get('#email').should('have.class', 'barraEmail');
      cy.get('#email').click();
      cy.get('#email').should('have.id', 'email');
      cy.get('#email').should('have.attr', 'type', 'email');
      cy.get('#email').click();
      cy.get('#email').should('have.attr', 'placeholder', 'Digite aqui seu email');
      cy.get('#email').should('be.visible');
      cy.get('#email').should('be.enabled');
      cy.get('#email').should('not.be.checked');
      cy.get('.botaoEmail').should('have.text', 'Login');
      cy.get('.botaoEmail').should('have.class', 'botaoEmail');
      cy.get('.botaoEmail').should('have.attr', 'type', 'submit');
      cy.get('.botaoEmail').should('be.visible');
      cy.get('.botaoEmail').should('be.enabled');
      cy.get('.redes-sociais').should('have.text', 'Midias Sociais');
      cy.get('.redes-sociais').should('have.class', 'redes-sociais');
      cy.get('.redes-sociais').should('be.visible');
      cy.get('.midias-sociais > :nth-child(1) > img').should('have.attr', 'src', './img/logo-discord.svg');
      cy.get('.midias-sociais > :nth-child(1) > img').should('be.visible');
      cy.get('.midias-sociais > :nth-child(2) > img').should('have.attr', 'src', './img/logo-instagram.svg');
      cy.get('.midias-sociais > :nth-child(2) > img').should('be.visible');
      cy.get('.midias-sociais > :nth-child(3) > img').should('have.attr', 'src', './img/logo-twitter.svg');
      cy.get('.midias-sociais > :nth-child(3) > img').should('be.visible');
      cy.get('.midias-sociais > :nth-child(4) > img').should('have.attr', 'src', './img/logo-youtube.svg');
      cy.get('.midias-sociais > :nth-child(4) > img').should('be.visible');
      cy.get('.midias-sociais').should('have.class', 'midias-sociais');
      cy.get('.midias-sociais').should('be.visible');
      cy.get('.copright-footer > h1').should('have.text', 'Copyright© 2023 Cyber-Motors. Todos os direitos reservados.');
      cy.get('.copright-footer > h1').should('be.visible');
      cy.get('.copright-footer > p').should('have.text', 'Sede em SENAI-Ipiranga Rua. Moreira de Godói, 226 - Ipiranga, São Paulo - SP, 04266-060');
      cy.get('.copright-footer > p').should('be.visible');
      cy.get('.devs-names > h1').should('have.text', 'Desenvolvedores:');
      cy.get('.devs-names > h1').should('be.visible');
      cy.get('.devs-names > :nth-child(2)').should('have.text', 'Bruno Leite Dos Santos');
      cy.get('.devs-names > :nth-child(2)').should('be.visible');
      cy.get('.devs-names > :nth-child(3)').should('have.text', 'Caio Matuti Destazio');
      cy.get('.devs-names > :nth-child(3)').should('be.visible');
      cy.get('.devs-names > :nth-child(4)').should('have.text', 'Fabio Luiz Silva Costa');
      cy.get('.devs-names > :nth-child(4)').should('be.visible');
      cy.get('.devs-names > :nth-child(5)').should('have.text', 'Felipe Wilquem Da Silva');
      cy.get('.devs-names > :nth-child(5)').should('be.visible');
      cy.get('.devs-names > :nth-child(6)').should('have.text', 'Gabriel Cavalcanti Barbosa');
      cy.get('.devs-names > :nth-child(6)').should('be.visible');
      cy.get('.devs-names > :nth-child(7)').should('have.text', 'Ingridy Estefany Moreno Souza Belini');
      cy.get('.devs-names > :nth-child(7)').should('be.visible');
      cy.get('.devs-names > :nth-child(8)').should('have.text', 'Melissa Vitória Da Silva Moya');
      cy.get('.devs-names > :nth-child(8)').should('be.visible');
      cy.get('.devs-names > :nth-child(9)').should('have.text', 'Nelson Zanferrari Sauer');
      cy.get('.devs-names > :nth-child(9)').should('be.visible');
      cy.get('.devs-names > :nth-child(10)').should('have.text', 'Renata Biagioni Wroblesk');
      cy.get('.devs-names > :nth-child(10)').should('be.visible');
      cy.get('.span-topo > a').should('have.text', 'Topo');
      cy.get('.span-topo > a').should('have.attr', 'href', '#topo-pagina');
      cy.get('.span-topo > a').should('be.visible');
      cy.get('.devs-names').should('have.class', 'devs-names');
      cy.get('.devs-names').should('be.visible');
      cy.get('.footerSpace').click();

      cy.get('footer').should('be.visible');
      /* ==== End Cypress Studio ==== */
    });
  });
});